spring.application.name=APIGateway

server.port=8083

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

spring.cloud.gateway.server.webmvc.routes[0].id=QuizService
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://QuizService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/quiz,/quiz/**,/quiz-test,/quiz-test/**,

spring.cloud.gateway.server.webmvc.routes[1].id=QuestionService
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://QuestionService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/question,/question/**